version: '3'
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../www/opencart-3.0.3.8:/var/www
      - ./storage:/var/storage/
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../www/opencart-3.0.3.8:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8181:80"
      - "443:443" 
    networks:
      - app-network
  db:   
    build:
      context: ./database

    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/data/:/docker-entrypoint-initdb.d/
      - ./database/data/my.cnf:/etc/mysql/my.cnf
      - ./database/data/mysql:/var/lib/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=opencart
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local